Warn about merging with autofix

diff --git a/bin/git-autofix b/bin/git-autofix
--- a/bin/git-autofix
+++ b/bin/git-autofix
@@ -1,6 +1,12 @@
-#!/bin/sh
+#!/bin/bash
 
 target="$(git rev-parse $1)"
+rebase_target=$target~1
+
+if ! git merge-base --is-ancestor $rebase_target HEAD && [[ $(git rev-list --count --merges $rebase_target..HEAD) = 0 ]]; then
+  echo "can't autofix past a merge commit"
+  exit 1
+fi
 
 if ! git commit --fixup=$target ; then
   echo "commit fail, aborting"
@@ -9,6 +15,6 @@ fi
 
 dirty="$(git diff --name-only --exit-code HEAD)"
 ( test -z "$dirty" || git stash ) &&
-GIT_EDITOR=cat git rebase --interactive --autosquash $target~1 &&
+GIT_EDITOR=cat git rebase --quiet --interactive --autosquash $rebase_target &&
 ( test -z "$dirty" || git stash pop )
 
